language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  # Requires the GH_TOKEN environment variable to have been set with a personal access token
  # with the public_repo or repo scope (repo is required for private repositories)
  #   see: https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings
  #   see: https://help.github.com/articles/creating-an-access-token-for-command-line-use/
  - yarn deploy-storybook --ci

# deploy:
#   # GitHub Pages Deployment (https://docs.travis-ci.com/user/deployment/pages/)
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master
#   local-dir: build
